FROM postgis/postgis:15-3.4

RUN apt-get update \
      && apt-get install -y curl \
      && apt-get install -y unzip \
      && apt-get install -y postgis \
      && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
      && unzip awscliv2.zip \
      &&./aws/install

COPY /scripts/ /docker-entrypoint-initdb.d/