########Maven build stage########
FROM maven:3.8.5-openjdk-17-slim AS builder
COPY springboot /home/app
RUN mvn -f /home/app/pom.xml clean -DskipTests=true install
RUN mvn -f /home/app/pom.xml -DskipTests=true package

########JRE run stage########
FROM openjdk:22-ea-17-jdk-slim-bullseye
COPY --from=builder /home/app/target/elevationtiles-0.0.1-SNAPSHOT.jar /usr/local/lib/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar", "/usr/local/lib/app.jar"]